"""Render one fixed-format, self-contained HALO batch diagnosis report."""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


_PAYLOAD_PREFIX = "const batch = "
_PAYLOAD_SCHEMA_VERSION = 2
_TEMPLATE_PATH = Path(__file__).resolve().parents[1] / "assets" / "halo_diagnostic_report.template.html"
DEFAULT_ARCHIVE_THRESHOLD = 500


def read_batch_payload(path: Path) -> dict[str, Any] | None:
    """Read the embedded payload from a report previously generated by this module."""
    if not path.is_file():
        return None
    document = path.read_text(encoding="utf-8")
    start = document.find(_PAYLOAD_PREFIX)
    if start < 0:
        raise ValueError(f"existing HTML is not a HALO batch report: {path}")
    start += len(_PAYLOAD_PREFIX)
    end = document.find(";\n", start)
    if end < 0:
        raise ValueError(f"existing HALO batch report payload is incomplete: {path}")
    try:
        payload = json.loads(document[start:end])
    except json.JSONDecodeError as exc:
        raise ValueError(f"existing HALO batch report payload is invalid: {path}") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("tasks"), list):
        raise ValueError(f"existing HALO batch report payload has an invalid structure: {path}")
    version = payload.get("payload_schema_version")
    if version not in (None, 1, _PAYLOAD_SCHEMA_VERSION):
        raise ValueError(f"unsupported HALO batch report payload version {version}: {path}")
    return payload


def _task_identity(task: dict[str, Any]) -> str:
    fingerprint = task.get("trace_fingerprint")
    if isinstance(fingerprint, str) and fingerprint:
        return f"task:{task.get('task_id')}:trace:{fingerprint}"
    return f"legacy-task:{task.get('task_id')}"


def _merge_tasks(
    existing_tasks: list[dict[str, Any]],
    current_tasks: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    current_by_identity = {_task_identity(task): task for task in current_tasks}
    current_task_ids = {str(task.get("task_id")) for task in current_tasks}
    merged: list[dict[str, Any]] = []
    for task in existing_tasks:
        task_key = _task_identity(task)
        if task_key in current_by_identity:
            continue
        if task_key.startswith("legacy-task:") and str(task.get("task_id")) in current_task_ids:
            continue
        merged.append(task)
    merged.extend(current_tasks)
    return merged


def _load_template() -> str:
    if not _TEMPLATE_PATH.is_file():
        raise FileNotFoundError(f"HALO HTML template is missing: {_TEMPLATE_PATH}")
    template = _TEMPLATE_PATH.read_text(encoding="utf-8")
    if template.count("__BATCH_DATA__") != 1:
        raise ValueError("HALO HTML template must contain exactly one __BATCH_DATA__ marker")
    return template


def _write_payload(output_path: Path, payload: dict[str, Any]) -> None:
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    encoded = encoded.replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    document = _load_template().replace("__BATCH_DATA__", encoded)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_name(f".{output_path.name}.{os.getpid()}.tmp")
    try:
        temporary_path.write_text(document, encoding="utf-8")
        os.replace(temporary_path, output_path)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def _next_archive_path(output_path: Path, generated_at: datetime) -> Path:
    stamp = generated_at.strftime("%Y%m%dT%H%M%SZ")
    candidate = output_path.with_name(f"{output_path.stem}.archive-{stamp}{output_path.suffix}")
    index = 2
    while candidate.exists():
        candidate = output_path.with_name(
            f"{output_path.stem}.archive-{stamp}-{index}{output_path.suffix}"
        )
        index += 1
    return candidate


def render_batch_report(
    output_path: Path,
    *,
    handoff_path: Path,
    diagnose_mode: str,
    tasks: list[dict[str, Any]],
    errors: list[str],
    archive_threshold: int = DEFAULT_ARCHIVE_THRESHOLD,
) -> list[Path]:
    if archive_threshold < 0:
        raise ValueError("archive_threshold must be >= 0")
    existing = read_batch_payload(output_path)
    existing_tasks = existing["tasks"] if existing is not None else []
    batch_runs = existing.get("batch_runs", 1) + 1 if existing is not None else 1
    generated_at = datetime.now(timezone.utc)
    merged_tasks = _merge_tasks(existing_tasks, tasks)
    archive_records = list(existing.get("archives", [])) if existing is not None else []
    archive_paths: list[Path] = []
    if archive_threshold and len(merged_tasks) > archive_threshold:
        archived_tasks = merged_tasks[:-archive_threshold]
        merged_tasks = merged_tasks[-archive_threshold:]
        for offset in range(0, len(archived_tasks), archive_threshold):
            archive_tasks = archived_tasks[offset:offset + archive_threshold]
            archive_path = _next_archive_path(output_path, generated_at)
            archive_payload = {
                "payload_schema_version": _PAYLOAD_SCHEMA_VERSION,
                "handoff": str(handoff_path),
                "diagnose_mode": diagnose_mode,
                "generated_at": generated_at.isoformat(),
                "batch_runs": batch_runs,
                "tasks": archive_tasks,
                "errors": [],
                "archives": [],
                "is_archive": True,
            }
            _write_payload(archive_path, archive_payload)
            archive_paths.append(archive_path)
            archive_records.append({
                "file": archive_path.name,
                "task_count": len(archive_tasks),
                "created_at": generated_at.isoformat(),
            })
    payload = {
        "payload_schema_version": _PAYLOAD_SCHEMA_VERSION,
        "handoff": str(handoff_path),
        "diagnose_mode": diagnose_mode,
        "generated_at": generated_at.isoformat(),
        "batch_runs": batch_runs,
        "tasks": merged_tasks,
        "errors": errors,
        "archives": archive_records,
        "is_archive": False,
    }
    _write_payload(output_path, payload)
    return archive_paths
