"""Render one fixed-format, self-contained HALO batch diagnosis report."""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


_PAYLOAD_PREFIX = "const batch = "
_PAYLOAD_SCHEMA_VERSION = 1


def read_batch_payload(path: Path) -> dict[str, Any] | None:
    """Read the embedded payload from a report previously generated by this module."""
    if not path.is_file():
        return None
    document = path.read_text(encoding="utf-8")
    start = document.find(_PAYLOAD_PREFIX)
    if start < 0:
        raise ValueError(f"existing HTML is not a HALO batch report: {path}")
    start += len(_PAYLOAD_PREFIX)
    end = document.find(";\n", start)
    if end < 0:
        raise ValueError(f"existing HALO batch report payload is incomplete: {path}")
    try:
        payload = json.loads(document[start:end])
    except json.JSONDecodeError as exc:
        raise ValueError(f"existing HALO batch report payload is invalid: {path}") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("tasks"), list):
        raise ValueError(f"existing HALO batch report payload has an invalid structure: {path}")
    version = payload.get("payload_schema_version")
    if version not in (None, _PAYLOAD_SCHEMA_VERSION):
        raise ValueError(f"unsupported HALO batch report payload version {version}: {path}")
    return payload


def _task_identity(task: dict[str, Any]) -> str:
    fingerprint = task.get("trace_fingerprint")
    if isinstance(fingerprint, str) and fingerprint:
        return f"task:{task.get('task_id')}:trace:{fingerprint}"
    return f"legacy-task:{task.get('task_id')}"


def _merge_tasks(
    existing_tasks: list[dict[str, Any]],
    current_tasks: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    current_by_identity = {_task_identity(task): task for task in current_tasks}
    current_legacy_by_task_id = {
        str(task.get("task_id")): task for task in current_tasks
    }
    merged: list[dict[str, Any]] = []
    seen: set[str] = set()
    for task in existing_tasks:
        task_key = _task_identity(task)
        replacement = current_by_identity.get(task_key)
        if replacement is None and task_key.startswith("legacy-task:"):
            replacement = current_legacy_by_task_id.get(str(task.get("task_id")))
        selected = replacement or task
        merged.append(selected)
        seen.add(_task_identity(selected))
    for task in current_tasks:
        task_key = _task_identity(task)
        if task_key not in seen:
            merged.append(task)
            seen.add(task_key)
    return merged


def render_batch_report(
    output_path: Path,
    *,
    handoff_path: Path,
    diagnose_mode: str,
    tasks: list[dict[str, Any]],
    errors: list[str],
) -> None:
    existing = read_batch_payload(output_path)
    existing_tasks = existing["tasks"] if existing is not None else []
    batch_runs = existing.get("batch_runs", 1) + 1 if existing is not None else 1
    payload = {
        "payload_schema_version": _PAYLOAD_SCHEMA_VERSION,
        "handoff": str(handoff_path),
        "diagnose_mode": diagnose_mode,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "batch_runs": batch_runs,
        "tasks": _merge_tasks(existing_tasks, tasks),
        "errors": errors,
    }
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    encoded = encoded.replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    document = _DOCUMENT.replace("__BATCH_DATA__", encoded)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_name(f".{output_path.name}.{os.getpid()}.tmp")
    try:
        temporary_path.write_text(document, encoding="utf-8")
        os.replace(temporary_path, output_path)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


_DOCUMENT = r'''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>小艺批次诊断报告</title>
  <style>
    :root {
      color-scheme: light dark;
      --page: light-dark(#f4f6fb, #10131a);
      --surface: light-dark(#ffffff, #191e28);
      --surface-soft: light-dark(#f7f9fc, #222936);
      --text: light-dark(#182033, #edf1f8);
      --muted: light-dark(#657089, #a6afc1);
      --border: light-dark(#dfe4ee, #343c4d);
      --blue: light-dark(#3568d4, #7da4ff);
      --blue-soft: light-dark(#eaf0ff, #202c49);
      --red: light-dark(#c33f4d, #ff7f8a);
      --red-soft: light-dark(#fff0f1, #43252c);
      --orange: light-dark(#b85b18, #ffac65);
      --orange-soft: light-dark(#fff4e9, #3f2d20);
      --yellow: light-dark(#956d08, #f4ce62);
      --yellow-soft: light-dark(#fff9dc, #3b351d);
      --green: light-dark(#237957, #62d6a5);
      --green-soft: light-dark(#eaf8f1, #1e3a31);
      --purple: light-dark(#7354ba, #b8a0ff);
      --purple-soft: light-dark(#f3efff, #302943);
      --shadow: 0 8px 24px color-mix(in srgb, var(--text) 8%, transparent);
    }
    * { box-sizing: border-box; }
    body { margin: 0; background: var(--page); color: var(--text); font-family: Inter, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif; }
    button, select { font: inherit; }
    .shell { width: min(1180px, calc(100% - 28px)); margin: 22px auto 48px; }
    .hero { background: linear-gradient(135deg, var(--surface) 0%, var(--blue-soft) 100%); border: 1px solid var(--border); border-radius: 18px 18px 0 0; padding: 24px; }
    .hero-top { display: flex; justify-content: space-between; gap: 20px; align-items: flex-start; }
    h1 { margin: 0; font-size: clamp(24px, 4vw, 34px); font-weight: 600; letter-spacing: -.02em; }
    .subtitle { margin: 8px 0 0; color: var(--muted); }
    .batch-chip { border: 1px solid color-mix(in srgb, var(--blue) 35%, var(--border)); border-radius: 999px; color: var(--blue); padding: 7px 11px; white-space: nowrap; }
    .metrics { display: grid; grid-template-columns: repeat(4, minmax(110px, 1fr)); gap: 10px; margin-top: 20px; }
    .metric { background: color-mix(in srgb, var(--surface) 85%, transparent); border: 1px solid var(--border); border-radius: 12px; padding: 12px 14px; }
    .metric-label { color: var(--muted); font-size: 12px; }
    .metric-value { display: block; font-size: 22px; font-weight: 600; margin-top: 2px; }
    .filter-dock { position: sticky; top: 0; z-index: 20; background: color-mix(in srgb, var(--surface) 96%, transparent); border: 1px solid var(--border); box-shadow: var(--shadow); padding: 12px 18px; backdrop-filter: blur(10px); }
    .filter-toggle { display: none; width: 100%; border: 0; background: transparent; color: var(--text); cursor: pointer; padding: 3px 0; text-align: left; }
    .filters { display: grid; grid-template-columns: repeat(6, minmax(0, 1fr)); gap: 9px; }
    label { color: var(--muted); display: grid; font-size: 12px; gap: 5px; }
    select { appearance: none; width: 100%; min-width: 0; border: 1px solid var(--border); border-radius: 9px; background-color: var(--surface); background-image: linear-gradient(45deg, transparent 50%, var(--muted) 50%), linear-gradient(135deg, var(--muted) 50%, transparent 50%); background-position: calc(100% - 15px) 50%, calc(100% - 10px) 50%; background-repeat: no-repeat; background-size: 5px 5px, 5px 5px; color: var(--text); padding: 8px 28px 8px 10px; }
    select:focus-visible, .filter-toggle:focus-visible, .task-toggle:focus-visible, .task-nav a:focus-visible, .evidence summary:focus-visible { outline: 2px solid var(--blue); outline-offset: 2px; }
    .content { border: 1px solid var(--border); border-top: 0; border-radius: 0 0 18px 18px; padding: 18px; }
    .report-layout { display: grid; grid-template-columns: 190px minmax(0, 1fr); gap: 16px; align-items: start; }
    .task-nav { position: sticky; top: 92px; max-height: calc(100vh - 112px); overflow: auto; background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 11px; }
    .task-nav-title { font-size: 13px; font-weight: 600; margin: 0 0 8px; }
    .task-nav-list { display: grid; gap: 4px; }
    .task-nav a { border-radius: 7px; color: var(--muted); display: block; font-size: 13px; overflow: hidden; padding: 7px 8px; text-decoration: none; text-overflow: ellipsis; white-space: nowrap; }
    .task-nav a:hover { background: var(--surface-soft); color: var(--text); }
    .report-main { min-width: 0; }
    .result-line { color: var(--muted); font-size: 13px; margin: 0 0 12px; }
    .task-list { display: grid; gap: 12px; }
    .task { position: relative; scroll-margin-top: 102px; background: var(--surface); border: 1px solid var(--border); border-radius: 14px; overflow: hidden; }
    .task::before { content: ""; position: absolute; inset: 0 auto 0 0; width: 5px; border-radius: 14px 0 0 14px; pointer-events: none; z-index: 1; }
    .task.color-0::before { background: var(--blue); }
    .task.color-1::before { background: var(--orange); }
    .task.color-2::before { background: var(--purple); }
    .task.color-3::before { background: var(--green); }
    .task.color-4::before { background: var(--red); }
    .task.color-5::before { background: var(--yellow); }
    .task-toggle { appearance: none; width: 100%; border: 0; background: transparent; color: inherit; cursor: pointer; display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: center; gap: 16px; padding: 15px 17px 15px 20px; text-align: left; }
    .task-toggle:hover { background: var(--surface-soft); }
    .task-main { min-width: 0; }
    .task-id { display: inline-block; font-size: 19px; font-weight: 600; margin-right: 10px; }
    .task-name { color: var(--muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .task-meta { display: flex; flex-wrap: wrap; justify-content: flex-end; align-items: center; gap: 7px; }
    .chip { display: inline-flex; align-items: center; border-radius: 999px; background: var(--surface-soft); color: var(--muted); font-size: 12px; padding: 5px 8px; white-space: nowrap; }
    .chip.failed { background: var(--red-soft); color: var(--red); }
    .chip.passed { background: var(--green-soft); color: var(--green); }
    .chip.missing, .chip.error { background: var(--yellow-soft); color: var(--yellow); }
    .chevron { color: var(--muted); font-size: 22px; transition: transform 160ms ease; }
    .task.open .chevron { transform: rotate(90deg); }
    .task-detail { display: none; border-top: 1px solid var(--border); padding: 18px; }
    .task.open .task-detail { display: block; }
    .summary { display: grid; grid-template-columns: 1fr auto; gap: 16px; align-items: start; background: var(--blue-soft); border-radius: 11px; padding: 13px 15px; margin-bottom: 16px; }
    .summary strong { display: block; margin-bottom: 4px; }
    .summary p { margin: 0; }
    .links { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 8px; }
    .links a { color: var(--blue); text-decoration: none; white-space: nowrap; }
    .links a:hover { text-decoration: underline; }
    .columns { display: grid; grid-template-columns: minmax(0, .95fr) minmax(0, 1.05fr); gap: 16px; align-items: start; }
    .section-title { display: flex; justify-content: space-between; align-items: center; margin: 0 0 9px; font-size: 15px; }
    .section-count { color: var(--muted); font-size: 12px; font-weight: 400; }
    .stack { display: grid; gap: 10px; }
    .finding, .change { background: var(--surface-soft); border-radius: 11px; padding: 13px; }
    .finding-head, .change-head { display: flex; justify-content: space-between; align-items: flex-start; gap: 10px; }
    .finding h3, .change h3 { margin: 0; font-size: 15px; font-weight: 600; }
    .finding p, .change p { margin: 8px 0 0; }
    .category { background: var(--red-soft); color: var(--red); border-radius: 999px; font-size: 12px; padding: 4px 8px; white-space: nowrap; }
    .change { background: var(--surface); border: 1px solid var(--border); }
    .change.p0 { border-left: 4px solid var(--red); }
    .change.p1 { border-left: 4px solid var(--orange); }
    .change.p2 { border-left: 4px solid var(--yellow); }
    .change.p3 { border-left: 4px solid var(--blue); }
    .change.p4 { border-left: 4px solid var(--purple); }
    .priority { border-radius: 6px; color: #fff; font-size: 12px; font-weight: 600; padding: 3px 6px; }
    .priority.p0 { background: var(--red); }
    .priority.p1 { background: var(--orange); }
    .priority.p2 { background: var(--yellow); }
    .priority.p3 { background: var(--blue); }
    .priority.p4 { background: var(--purple); }
    .change-title { display: flex; gap: 8px; align-items: center; }
    .component { color: var(--purple); background: var(--purple-soft); border-radius: 999px; font-size: 12px; padding: 4px 8px; white-space: nowrap; }
    .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 9px; margin-top: 10px; }
    .field { color: var(--muted); font-size: 13px; }
    .field strong { color: var(--text); display: block; font-size: 12px; margin-bottom: 2px; }
    .refs { color: var(--muted); font-size: 12px; margin-top: 8px; }
    .evidence { margin-top: 9px; }
    .evidence summary { color: var(--blue); cursor: pointer; font-size: 13px; }
    .evidence-list { display: grid; gap: 7px; margin-top: 8px; }
    .evidence-item { background: color-mix(in srgb, var(--surface) 75%, transparent); border-radius: 8px; padding: 9px; font-size: 12px; }
    code { color: var(--purple); overflow-wrap: anywhere; }
    .raw-error { color: var(--red); margin-top: 4px; overflow-wrap: anywhere; }
    .empty { color: var(--muted); padding: 18px; text-align: center; }
    .batch-errors { margin-top: 14px; background: var(--red-soft); color: var(--red); border-radius: 11px; padding: 12px 14px; }
    .batch-errors ul { margin: 7px 0 0; padding-left: 20px; }
    @media (max-width: 880px) { .filters { grid-template-columns: repeat(3, 1fr); } .report-layout { grid-template-columns: 1fr; } .task-nav { position: static; max-height: none; } .task-nav-list { grid-template-columns: repeat(3, minmax(0, 1fr)); } .columns { grid-template-columns: 1fr; } }
    @media (max-width: 620px) { .shell { width: min(100% - 16px, 1180px); margin-top: 8px; } .hero-top, .summary { grid-template-columns: 1fr; display: grid; } .metrics { grid-template-columns: repeat(2, 1fr); } .filter-toggle { display: block; } .filter-dock.filters-collapsed .filters { display: none; } .filters { grid-template-columns: repeat(2, 1fr); margin-top: 10px; } .task-nav-list { grid-template-columns: repeat(2, minmax(0, 1fr)); } .task-toggle { grid-template-columns: 1fr; } .task-meta { justify-content: flex-start; } .links { justify-content: flex-start; } .field-grid { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <div class="hero-top"><div><h1>小艺批次诊断报告</h1><p class="subtitle" id="subtitle"></p></div><span class="batch-chip" id="mode-chip"></span></div>
      <div class="metrics" id="metrics"></div>
    </section>
    <section class="filter-dock" aria-label="批次筛选">
      <button type="button" class="filter-toggle" id="filter-toggle" aria-expanded="true">收起筛选</button>
      <div class="filters">
        <label>任务<select id="filter-task"><option value="">全部任务</option></select></label>
        <label>Judge<select id="filter-judge"><option value="">全部状态</option><option value="failed">未通过</option><option value="passed">通过</option><option value="missing">缺失</option><option value="error">异常</option></select></label>
        <label>执行分类<select id="filter-classification"><option value="">全部分类</option></select></label>
        <label>错误类别<select id="filter-category"><option value="">全部类别</option></select></label>
        <label>建议优先级<select id="filter-priority"><option value="">全部优先级</option><option>P0</option><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select></label>
        <label>建议组件<select id="filter-component"><option value="">全部组件</option></select></label>
      </div>
    </section>
    <section class="content">
      <div class="report-layout">
        <nav class="task-nav" aria-label="任务目录">
          <h2 class="task-nav-title">任务目录</h2>
          <div class="task-nav-list" id="task-nav-list"></div>
        </nav>
        <div class="report-main">
          <p class="result-line" id="result-line"></p>
          <div class="task-list" id="task-list"></div>
          <div id="batch-errors"></div>
        </div>
      </div>
    </section>
  </main>
  <script>
  (() => {
    'use strict';
    const batch = __BATCH_DATA__;
    const priorityRank = {P0: 0, P1: 1, P2: 2, P3: 3, P4: 4};
    const categoryLabels = {
      ENVIRONMENT_FAILURE: '环境依赖问题', TOOL_FAILURE: '工具调用失败', WRONG_TOOL_USAGE: '工具使用错误',
      DATA_EXTRACTION_ERROR: '数据提取错误', SOURCE_DATA_MISMATCH: '源数据不匹配', CHART_TYPE_ERROR: '图表类型错误',
      OUTPUT_VALIDATION_FAILURE: '输出验证失败', VERIFICATION_FAILURE: '验证失败', OUTPUT_FORMAT_ERROR: '输出格式错误',
      MISSING_OUTPUT_FILE: '输出文件缺失', CONTENT_ERROR: '内容错误', TASK_MISINTERPRETATION: '任务理解偏差',
      WORKFLOW_INEFFICIENCY: '执行流程低效', RECOVERY_FAILURE: '恢复失败', JUDGE_FAILURE: 'Judge 失败'
    };
    const classificationLabels = {
      FAILED: '执行失败', SUCCEEDED_WITH_RECOVERED_ERRORS: '成功且错误已恢复',
      SUCCEEDED_WITH_UNPROVEN_RECOVERY: '成功但恢复未验证', SUCCEEDED_CLEANLY: '干净成功', UNKNOWN: '状态未知'
    };
    const taskCounts = batch.tasks.reduce((counts, task) => counts.set(String(task.task_id), (counts.get(String(task.task_id)) || 0) + 1), new Map());
    const state = {open: new Set()};
    const $ = (id) => document.getElementById(id);
    const el = (tag, className = '', text = '') => { const node = document.createElement(tag); if (className) node.className = className; if (text !== '') node.textContent = text; return node; };
    const option = (value, label) => { const node = el('option', '', label); node.value = value; return node; };
    const categoryLabel = (value) => categoryLabels[value] || `其他问题 · ${String(value || '未分类').replaceAll('_', ' ')}`;
    const taskLabel = (task) => task.task || `task${task.task_id}`;
    const taskIdentity = (task) => task.trace_fingerprint ? `task:${task.task_id}:trace:${task.trace_fingerprint}` : `legacy-task:${task.task_id}`;
    const taskDisplayId = (task) => taskCounts.get(String(task.task_id)) > 1 && task.trace_fingerprint ? `task${task.task_id} · ${task.trace_fingerprint.slice(0, 8)}` : `task${task.task_id}`;
    const taskDomId = (task) => `task-${taskIdentity(task).replace(/[^a-zA-Z0-9_-]/g, '-')}`;
    const judgeKind = (task) => task.judge_status === 'success' ? (task.judge_passed ? 'passed' : 'failed') : (task.judge_status === 'missing' ? 'missing' : 'error');
    const judgeText = (task) => { const kind = judgeKind(task); const score = typeof task.judge_score === 'number' ? ` · ${task.judge_score.toFixed(2)}` : ''; return kind === 'passed' ? `Judge 通过${score}` : kind === 'failed' ? `Judge 未通过${score}` : kind === 'missing' ? 'Judge 缺失' : 'Judge 异常'; };
    const link = (href, text) => { const node = el('a', '', text); node.href = href; node.target = '_blank'; node.rel = 'noreferrer'; return node; };

    function mergeChanges(changes) {
      const merged = new Map();
      (changes || []).forEach((change) => {
        const key = JSON.stringify([change.priority, change.component, change.target, change.title, change.problem, change.implementation, change.acceptance_criteria, change.expected_impact]);
        if (!merged.has(key)) merged.set(key, {...change, error_refs: []});
        const item = merged.get(key);
        item.error_refs = [...new Set([...item.error_refs, ...(change.error_refs || [])])];
      });
      return [...merged.values()].sort((a, b) => (priorityRank[a.priority] ?? 9) - (priorityRank[b.priority] ?? 9));
    }

    function currentFilters() {
      return {task: $('filter-task').value, judge: $('filter-judge').value, classification: $('filter-classification').value, category: $('filter-category').value, priority: $('filter-priority').value, component: $('filter-component').value};
    }

    function taskView(task) {
      const filters = currentFilters();
      if (filters.task && taskIdentity(task) !== filters.task) return null;
      if (filters.judge && judgeKind(task) !== filters.judge) return null;
      if (filters.classification && task.execution_classification !== filters.classification) return null;
      const allFindings = [...(task.error_findings || [])].sort((a, b) => (priorityRank[a.priority] ?? 9) - (priorityRank[b.priority] ?? 9));
      const findings = filters.category ? allFindings.filter((item) => item.category === filters.category) : allFindings;
      if (filters.category && !findings.length) return null;
      const visibleRefs = new Set(findings.map((item) => item.error_id));
      let changes = mergeChanges(task.proposed_changes || []);
      if (filters.category) changes = changes.filter((item) => (item.error_refs || []).some((ref) => visibleRefs.has(ref)));
      if (filters.priority) changes = changes.filter((item) => item.priority === filters.priority);
      if (filters.component) changes = changes.filter((item) => item.component === filters.component);
      if ((filters.priority || filters.component) && !changes.length) return null;
      return {task, findings, changes};
    }

    function renderEvidence(items) {
      const details = el('details', 'evidence');
      const summary = el('summary', '', `查看证据（${(items || []).length}）`);
      const list = el('div', 'evidence-list');
      (items || []).forEach((item) => {
        const card = el('div', 'evidence-item');
        const line = el('div');
        line.append(el('strong', '', `${item.source || 'TRACE'} · `), el('code', '', item.reference || '—'));
        if (item.tool) line.append(document.createTextNode(` · ${item.tool}`));
        card.append(line, el('div', '', item.fact || ''));
        if (item.error) card.append(el('div', 'raw-error', item.error));
        list.append(card);
      });
      details.append(summary, list);
      return details;
    }

    function renderFinding(item) {
      const card = el('article', 'finding');
      const head = el('div', 'finding-head');
      head.append(el('h3', '', `${item.error_id || ''} · ${item.title || '未命名问题'}`), el('span', 'category', categoryLabel(item.category)));
      card.append(head, el('p', '', item.summary || ''));
      const grid = el('div', 'field-grid');
      const cause = el('div', 'field'); cause.append(el('strong', '', '根因'), document.createTextNode(item.root_cause || '—'));
      const impact = el('div', 'field'); impact.append(el('strong', '', '影响'), document.createTextNode(item.impact || '—'));
      grid.append(cause, impact); card.append(grid);
      if ((item.evidence || []).length) card.append(renderEvidence(item.evidence));
      return card;
    }

    function renderChange(item, task) {
      const card = el('article', `change ${(item.priority || 'p4').toLowerCase()}`);
      const head = el('div', 'change-head');
      const title = el('div', 'change-title');
      title.append(el('span', `priority ${(item.priority || 'P4').toLowerCase()}`, item.priority || 'P4'), el('h3', '', item.title || '未命名建议'));
      head.append(title, el('span', 'component', item.component || 'unknown'));
      card.append(head, el('p', '', item.problem || ''));
      const grid = el('div', 'field-grid');
      const implementation = el('div', 'field'); implementation.append(el('strong', '', '实施方式'), document.createTextNode(item.implementation || '—'));
      const impact = el('div', 'field'); impact.append(el('strong', '', '预期收益'), document.createTextNode(item.expected_impact || '—'));
      grid.append(implementation, impact); card.append(grid);
      const criteria = item.acceptance_criteria || [];
      if (criteria.length) { const field = el('div', 'field'); field.append(el('strong', '', '验收标准'), document.createTextNode(criteria.join('；'))); card.append(field); }
      const names = (item.error_refs || []).map((ref) => { const finding = (task.error_findings || []).find((candidate) => candidate.error_id === ref); return finding ? `${ref} ${finding.title}` : ref; });
      if (names.length) card.append(el('div', 'refs', `关联问题：${names.join('；')}`));
      return card;
    }

    function renderTask(view, colorIndex) {
      const {task, findings, changes} = view;
      const identity = taskIdentity(task);
      const article = el('article', `task color-${colorIndex % 6}${state.open.has(identity) ? ' open' : ''}`);
      article.id = taskDomId(task);
      const toggle = el('button', 'task-toggle'); toggle.type = 'button'; toggle.setAttribute('aria-expanded', String(state.open.has(identity)));
      const main = el('div', 'task-main'); main.append(el('span', 'task-id', taskDisplayId(task)), el('span', 'task-name', taskLabel(task)));
      const meta = el('div', 'task-meta'); meta.append(el('span', `chip ${judgeKind(task)}`, judgeText(task)), el('span', 'chip', `${findings.length} 个问题`), el('span', 'chip', `${changes.length} 条建议`), el('span', 'chevron', '›'));
      toggle.append(main, meta);
      toggle.addEventListener('click', () => { if (state.open.has(identity)) state.open.delete(identity); else state.open.add(identity); render(); });
      article.append(toggle);
      const detail = el('div', 'task-detail');
      const summary = el('div', 'summary');
      const summaryText = el('div'); summaryText.append(el('strong', '', classificationLabels[task.execution_classification] || task.execution_classification || '尚无诊断'), el('p', '', task.primary_failure_mode || task.halo_message || '无可用诊断结论。'));
      const links = el('div', 'links');
      if (task.report_uri) links.append(link(task.report_uri, '诊断结果 ↗'));
      if (task.judge_result_uri) links.append(link(task.judge_result_uri, 'Judge 结果 ↗'));
      if (task.trace_uri) links.append(link(task.trace_uri, 'Trace ↗'));
      summary.append(summaryText, links); detail.append(summary);
      const columns = el('div', 'columns');
      const left = el('section'); const leftTitle = el('h2', 'section-title'); leftTitle.append(document.createTextNode('问题'), el('span', 'section-count', `${findings.length} 项`)); const leftStack = el('div', 'stack'); findings.forEach((item) => leftStack.append(renderFinding(item))); if (!findings.length) leftStack.append(el('div', 'empty', '没有匹配的问题')); left.append(leftTitle, leftStack);
      const right = el('section'); const rightTitle = el('h2', 'section-title'); rightTitle.append(document.createTextNode('优化建议'), el('span', 'section-count', `${changes.length} 项`)); const rightStack = el('div', 'stack'); changes.forEach((item) => rightStack.append(renderChange(item, task))); if (!changes.length) rightStack.append(el('div', 'empty', '没有匹配的建议')); right.append(rightTitle, rightStack);
      columns.append(left, right); detail.append(columns); article.append(detail);
      return article;
    }

    function populate() {
      batch.tasks.forEach((task) => $('filter-task').append(option(taskIdentity(task), taskDisplayId(task))));
      [...new Set(batch.tasks.map((task) => task.execution_classification).filter(Boolean))].sort().forEach((value) => $('filter-classification').append(option(value, classificationLabels[value] || value)));
      [...new Set(batch.tasks.flatMap((task) => (task.error_findings || []).map((item) => item.category)).filter(Boolean))].sort().forEach((value) => $('filter-category').append(option(value, categoryLabel(value))));
      [...new Set(batch.tasks.flatMap((task) => (task.proposed_changes || []).map((item) => item.component)).filter(Boolean))].sort().forEach((value) => $('filter-component').append(option(value, value)));
      document.querySelectorAll('select').forEach((select) => select.addEventListener('change', render));
      const toggle = $('filter-toggle');
      const setCollapsed = (collapsed) => {
        document.querySelector('.filter-dock').classList.toggle('filters-collapsed', collapsed);
        toggle.setAttribute('aria-expanded', String(!collapsed));
        toggle.textContent = collapsed ? '展开筛选' : '收起筛选';
      };
      setCollapsed(window.matchMedia('(max-width: 620px)').matches);
      toggle.addEventListener('click', () => setCollapsed(toggle.getAttribute('aria-expanded') === 'true'));
    }

    function renderMetrics() {
      const reported = batch.tasks.filter((task) => task.halo_status === 'success').length;
      const failedJudge = batch.tasks.filter((task) => judgeKind(task) === 'failed').length;
      const problems = batch.tasks.reduce((sum, task) => sum + (task.error_findings || []).length, 0);
      const changes = batch.tasks.reduce((sum, task) => sum + mergeChanges(task.proposed_changes || []).length, 0);
      const values = [['批次任务', batch.tasks.length], ['完成诊断', reported], ['Judge 未通过', failedJudge], ['优化建议', changes]];
      const root = $('metrics'); values.forEach(([label, value]) => { const card = el('div', 'metric'); card.append(el('span', 'metric-label', label), el('span', 'metric-value', String(value))); root.append(card); });
      $('subtitle').textContent = `累计 ${batch.batch_runs || 1} 次批跑 · 基于 Judge、Trace 与 HALO v6 报告 · ${new Date(batch.generated_at).toLocaleString('zh-CN')}`;
      const modeText = batch.diagnose_mode === 'failed' ? '仅诊断错误任务' : '诊断全部 Trace';
      $('mode-chip').textContent = `${batch.tasks.length} 个累计任务 · ${modeText}`;
    }

    function render() {
      const views = batch.tasks.map(taskView).filter(Boolean);
      const list = $('task-list'); list.replaceChildren();
      const navigation = $('task-nav-list'); navigation.replaceChildren();
      views.forEach((view) => {
        const identity = taskIdentity(view.task);
        list.append(renderTask(view, batch.tasks.findIndex((task) => taskIdentity(task) === identity)));
        const item = el('a', '', taskDisplayId(view.task));
        item.href = `#${taskDomId(view.task)}`;
        navigation.append(item);
      });
      if (!views.length) list.append(el('div', 'empty', '没有符合当前筛选条件的任务'));
      $('result-line').textContent = `当前显示 ${views.length} / ${batch.tasks.length} 个任务；任务默认折叠。`;
    }

    function renderBatchErrors() {
      if (!batch.errors.length) return;
      const box = el('div', 'batch-errors'); box.append(el('strong', '', `未生成有效诊断的任务（${batch.errors.length}）`)); const list = el('ul'); batch.errors.forEach((message) => { const item = el('li', '', message); list.append(item); }); box.append(list); $('batch-errors').append(box);
    }

    populate(); renderMetrics(); renderBatchErrors(); render();
  })();
  </script>
</body>
</html>
'''
